name: Mise a jour Automatique CarbuNet

on:
  schedule:
    # S'exécute à 7h et 16h UTC (9h et 18h en France)
    - cron: '0 7,16 * * *' 
  workflow_dispatch: # Bouton pour tester manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Recupere le code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Récupère tout l'historique pour éviter les conflits

      - name: Installe Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installe les outils
        run: pip install pandas sqlalchemy pymysql GitPython cryptography openpyxl

      - name: Execute le nettoyage
        run: python maj_auto.py

      - name: Envoi sur GitHub (Force Mode)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add carburant_prix_nettoye.csv
          git commit -m "MàJ auto Cloud (Robot)" || exit 0
          git push origin main --force