name: Mise a jour Automatique CarbuNet

on:
  schedule:
    - cron: '0 7,16 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Recupere le code
        uses: actions/checkout@v4 # Version plus récente
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Installe Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installe les outils
        run: pip install pandas sqlalchemy pymysql GitPython cryptography openpyxl

      - name: Execute le nettoyage
        run: python maj_auto.py

      - name: Envoi sur GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add carburant_prix_nettoye.csv
          git commit -m "MàJ automatique des prix" || exit 0
          git push origin main --force